# Generated by Django 3.0.3 on 2020-06-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0002_auto_20200531_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='priority',
            field=models.CharField(choices=[('act', 'Active'), ('com', 'Сompleted')], default='act', max_length=3),
        ),
    ]
