# Generated by Django 3.0.3 on 2020-06-03 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0003_article_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='priority',
            new_name='status',
        ),
    ]
