# Generated by Django 3.0.3 on 2020-06-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0004_auto_20200603_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Активна', 'Active'), ('Выполнена', 'Сompleted')], default='Active', max_length=9),
        ),
    ]
