# Generated by Django 3.0.3 on 2020-06-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0005_auto_20200603_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to='MyBlog.Friends'),
        ),
    ]
